version: '3'
services:
  nginx:
    image: fibon4code/multi-nginx
    memlimit: 128m
    hostname: nginx
    ports:
      - 80:80
  server:
    image: fibon4code/multi-server
    memlimit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=p@ssw0rd
      - PGPORT=5432
  client:
    image: fibon4code/multi-client
    memlimit: 128m
    hostname: client
  worker:
    image: fibon4code/multi-worker
    memlimit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
